-- Tightens three constraints left open since the initial schema.
--
-- 1. messages.body is nullable with no link to is_system. The client always writes a string, even an empty
--    one for the message carrying a poll, but nothing at the database level stops a user message with
--    body = null: the conversation would then show an empty bubble, impossible to edit or to understand.
--    Only system messages, generated by the database and rendered from a translated label, have a reason not
--    to carry text.
--
-- 2. poll_options has no uniqueness on (poll_id, position). Positions come from the array index at creation,
--    so they are distinct in practice, but two offline clients replaying their queue can end up with two
--    options of the same rank in the same poll. The displayed order then depends on the luck of the sort, and
--    the list of options can change order on every reload.
--
-- 3. households has no delete policy: the only possible deletion goes through redeem_invite, in security
--    definer, during a household transfer. An owner therefore cannot dissolve their household. We open the
--    minimal case with no side effect: the owner of a household of which they are the last member. Deleting a
--    household still lived in would make the other members' lists and messages disappear in cascade, which is
--    not a decision for the owner alone. redeem_invite goes on overriding this, security definer not being
--    subject to policies.

alter table public.messages
  add constraint messages_body_required check (is_system or body is not null);

alter table public.poll_options
  add constraint poll_options_poll_position_key unique (poll_id, position);

create or replace function public.is_household_sole_member(target uuid)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select not exists (
    select 1
    from public.household_members m
    where m.household_id = target
      and m.user_id <> (select auth.uid())
  )
$$;

comment on function public.is_household_sole_member(uuid) is
  'Vrai si l appelant est le seul membre du foyer. Security definer pour ne pas dependre de ce que la policy de lecture de household_members laisse voir.';

create policy households_delete on public.households for delete
  using (public.is_household_owner(id) and public.is_household_sole_member(id));
